//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iinvest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> quanity { get; set; }
        public string ticker { get; set; }
        public string risk { get; set; }
        public Nullable<double> PEratio { get; set; }
        public string Id { get; set; }
    }
}
